# Generated by Django 5.2.12 on 2026-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='acessorios',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(blank=True, null=True, related_name='acessorios', to='core.acessorio'),
        ),
    ]
